### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by tuskpot**
This pull request includes various corrections and editorial changes. I think that all of these the editorial changes are supported by the typography manual, but let me know if I've gone too far on any of this.

* Modernize "Buda-Pesth" to "Budapest". [Google Ngrams](https://books.google.com/ngrams/graph?content=Buda-Pesth%2CBudapest&year_start=1800&year_end=2000&corpus=15&smoothing=3&share=&direct_url=t1%3B%2CBuda%20-%20Pesth%3B%2Cc0%3B.t1%3B%2CBudapest%3B%2Cc0#t1%3B%2CBuda%20-%20Pesth%3B%2Cc0%3B.t1%3B%2CBudapest%3B%2Cc0) suggests that this was more common around the 1890s, but it's now obsolete.
* Modernize various spellings with the æ ligature -> hemmorhage, anemic, aetet/aet., "Omnia Romae…"
* Modernize spelling by removing some old-fashioned umlauts -> aerated, aerial, zoological, zoophagous.
* Remove quotation marks around some building names.
* Replace quotation marks around newspaper names with italics, and semanticate them.
* Correct a couple transcription errors in punctuation to match the source scans.

I have a few other issues that I'm not so sure about. I'll send the details to the mailing list for feedback before putting in a pull request.

### CODE REVIEW

**Comment by acabal** [comment]
Hi there, thanks! I think we can accept almost all of these except I think we should keep quotes around `Spaniards` here, for clarity; so that it's clear they're not picking up a cab by a group of Spanish people. Can you make that tweak? Thanks!

**Comment by acabal** [comment]
You know what, I've thought about it a little more, and I think the epistolary style of the novel means it might be best to preserve some of these stranger spellings as part of the prose style. I.e. it's what was "in the letters" versus run-of-the-mill prose.  Let's just leave them as-is for now. However we can continue to italicize the newspapers and remove quotes from place names (except the one).

**Comment by tuskpot** [comment]
Okay, no problem. I think it will be cleaner to make a separate branch with the changes that we want, so I'm going to close this pull request and then make a new one on the new branch.

**Comment by acabal** [comment]
OK great. Let's also put a note in the production-notes that we considered some of these changes but decided against them, so future readers know.

**Pull request closed without merging**
